/**
 * withTurtleLiveActivity — our Live Activity layout, made durable.
 *
 * ─── The problem ────────────────────────────────────────────────────────────
 *
 * The lock-screen card is a NATIVE widget extension. Its layout is SwiftUI that
 * expo-live-activity ships in its own `ios-files/`, and its config plugin
 * copies that directory into `ios/LiveActivity/` on every prebuild. The plugin
 * takes no option for a different source, so there are only bad places to put
 * an edit:
 *   • node_modules — wiped by the next `npm install`, and invisible in review;
 *   • ios/LiveActivity — regenerated by the next prebuild;
 *   • a fork of the library — a whole dependency to carry for one view.
 *
 * ─── What this does ─────────────────────────────────────────────────────────
 *
 * Runs AFTER the library's plugin (order matters: it is listed after
 * "expo-live-activity" in app.json) and writes our copy of the view over the
 * one just copied in. The edit lives in `ios-widget/LiveActivityView.swift`,
 * in the repo, diffable, and survives both an install and a prebuild.
 *
 * Deliberately narrow: ONE file, and it fails LOUDLY if that file is missing
 * rather than silently shipping the library's layout — a lock-screen card that
 * quietly reverts is the kind of thing nobody notices for a month.
 *
 * NOTE: a change here is NATIVE. It reaches a phone through an EAS build and a
 * reinstall, never through an over-the-air update.
 */
const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('expo/config-plugins');

/** The widget extension's target name, fixed by the library's own plugin. */
const TARGET = 'LiveActivity';
const FILE = 'LiveActivityView.swift';

const withTurtleLiveActivity = (config) => withDangerousMod(config, [
  'ios',
  (cfg) => {
    const source = path.join(cfg.modRequest.projectRoot, 'ios-widget', FILE);
    if (!fs.existsSync(source)) {
      throw new Error(
        `[withTurtleLiveActivity] ${path.relative(cfg.modRequest.projectRoot, source)} is missing. `
        + 'Without it the build would silently ship the library\'s default lock-screen layout.',
      );
    }
    const targetDir = path.join(cfg.modRequest.platformProjectRoot, TARGET);
    if (!fs.existsSync(targetDir)) fs.mkdirSync(targetDir, { recursive: true });
    fs.copyFileSync(source, path.join(targetDir, FILE));
    return cfg;
  },
]);

module.exports = withTurtleLiveActivity;
