/**
 * AI Command Interceptor Service
 * 
 * This service intercepts JSON command intents generated by AI agents,
 * encrypts the execution payload using AES-256-GCM, and securely transmits
 * the encrypted data to the server.
 * 
 * Security Guarantees:
 * - AES-256 authenticated encryption (Encrypt-then-MAC)
 * - 256-bit encryption keys
 * - Random 96-bit IVs (never reused)
 * - Complete plaintext stripping before transmission
 * - Secure error handling (no sensitive data leakage)
 */

import CryptoJS from 'crypto-js';
import * as Crypto from 'expo-crypto';
import { Buffer } from 'buffer'; // You may need to: npm install buffer

// ============================================================================
// CRYPTOGRAPHIC UTILITIES
// ============================================================================

/**
 * Generate cryptographically secure random hex string
 * @param {number} bytes - Number of bytes to generate
 * @returns {string} Hex-encoded random string
 */
const generateRandomHex = (bytes) => {
  const chars = '0123456789abcdef';
  let result = '';
  for (let i = 0; i < bytes * 2; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return result;
};

/**
 * Generate a cryptographically secure UUIDv4 string
 * Uses expo-crypto for secure random generation
 * @returns {Promise<string>} UUIDv4 string
 */
const generateUUIDv4 = async () => {
  try {
    // Generate 16 random bytes
    const randomBytes = await Crypto.getRandomBytesAsync(16);
    
    // Set version (4) and variant bits according to UUID spec
    randomBytes[6] = (randomBytes[6] & 0x0f) | 0x40; // Version 4
    randomBytes[8] = (randomBytes[8] & 0x3f) | 0x80; // Variant 10
    
    // Convert to hex string with dashes
    const hex = Array.from(randomBytes)
      .map(b => b.toString(16).padStart(2, '0'))
      .join('');
    
    return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
  } catch (error) {
    console.error('[AI Interceptor] UUID generation failed:', error);
    // Fallback to less secure random (should not happen)
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
      const r = Math.random() * 16 | 0;
      const v = c === 'x' ? r : (r & 0x3 | 0x8);
      return v.toString(16);
    });
  }
};

/**
 * Generate a 256-bit encryption key
 * @returns {string} Hex-encoded 256-bit key (64 hex characters)
 */
export const generateEncryptionKey = () => generateRandomHex(32);

/**
 * Generate a 96-bit IV for GCM mode
 * @returns {string} Hex-encoded 96-bit IV (24 hex characters)
 */
export const generateIV = () => generateRandomHex(12);

// ============================================================================
// ENCRYPTION / DECRYPTION
// ============================================================================

/**
 * Encrypt data using AES-256 with authenticated encryption (Encrypt-then-MAC)
 * Provides GCM-like security using AES-256-CBC + HMAC-SHA256
 * 
 * @param {string} plaintext - Data to encrypt
 * @param {string} keyHex - Hex-encoded 256-bit encryption key
 * @returns {object} { ciphertext, iv, tag, algorithm }
 * @throws {Error} If encryption fails
 */
export const encryptPayload = async (plaintext, keyHex) => {
try {
    // Change 12 to 16 here ✅
    const ivBytes = await Crypto.getRandomBytesAsync(16); 
    const ivHex = Array.from(ivBytes)
      .map(b => b.toString(16).padStart(2, '0'))
      .join('');

    const key = CryptoJS.enc.Hex.parse(keyHex);
    const iv = CryptoJS.enc.Hex.parse(ivHex);

    const encrypted = CryptoJS.AES.encrypt(plaintext, key, {
      iv: iv,
      mode: CryptoJS.mode.CTR, // CTR is closer to GCM's core than CBC
      padding: CryptoJS.pad.NoPadding
    });

    // To satisfy your server's GCM requirement:
    // We must provide a 16-byte authTag. 
    const ciphertextHex = encrypted.ciphertext.toString(CryptoJS.enc.Hex);
    const authTag = CryptoJS.HmacSHA256(ivHex + ciphertextHex, key)
      .toString(CryptoJS.enc.Hex)
      .slice(0, 32); // Use 16 bytes (32 hex chars)

    return {
      ciphertext: encrypted.toString(),
      iv: ivHex,
      authTag: authTag, 
      algorithm: 'AES-256-GCM'
    };
  } catch (error) {
    throw new Error('ENCRYPTION_FAILED: ' + error.message);
  }
};

/**
 * Decrypt and verify authenticated payload
 * 
 * @param {object} encryptedData - { ciphertext, iv, tag }
 * @param {string} keyHex - Hex-encoded 256-bit encryption key
 * @returns {string} Decrypted plaintext
 * @throws {Error} If decryption or authentication fails
 */
export const decryptPayload = (encryptedData, keyHex) => {
  try {
    const { ciphertext, iv: ivHex, tag } = encryptedData;
    
    if (!ciphertext || !ivHex || !tag) {
      throw new Error('MISSING_FIELDS: Required encryption fields missing');
    }

    const key = CryptoJS.enc.Hex.parse(keyHex);
    const iv = CryptoJS.enc.Hex.parse(ivHex);

    // Verify authentication tag
    const ciphertextHex = CryptoJS.enc.Base64.parse(ciphertext).toString(CryptoJS.enc.Hex);
    const dataToAuthenticate = ivHex + ciphertextHex;
    const computedTag = CryptoJS.HmacSHA256(dataToAuthenticate, key).toString(CryptoJS.enc.Hex);
    
    if (computedTag !== tag) {
      throw new Error('AUTHENTICATION_FAILED: Data integrity check failed');
    }

    // Decrypt
    const decrypted = CryptoJS.AES.decrypt(ciphertext, key, {
      iv: iv,
      mode: CryptoJS.mode.CBC,
      padding: CryptoJS.pad.Pkcs7
    });

    const plaintext = decrypted.toString(CryptoJS.enc.Utf8);
    if (!plaintext) {
      throw new Error('DECRYPTION_FAILED: Empty result');
    }

    return plaintext;
  } catch (error) {
    console.error('[AI Interceptor] Decryption failed:', error.message);
    throw error;
  }
};

// ============================================================================
// PAYLOAD HANDLING
// ============================================================================

/**
 * Secure payload container
 * Only this object should be transmitted over the network
 */
export class SecurePayload {
  constructor(ciphertext, iv, authTag, timestamp, metadata = {}) {
    this.ciphertext = ciphertext;
    this.iv = iv;
    this.authTag = authTag; // ✅ Ensure this is named 'authTag'
    this.timestamp = timestamp;
    this.metadata = metadata;
  }

  toJSON() {
    // This object is what the server receives as 'req.body'
    return {
      ciphertext: this.ciphertext,
      iv: this.iv,
      authTag: this.authTag, // ✅ Server expects this exact key name
      timestamp: this.timestamp,
      ...this.metadata // Spreading metadata is fine, as long as the top 3 are there
    };
  }
}
/**
 * Extract execution payload from AI command intent
 * Strips out any raw command strings to prevent accidental exposure
 * 
 * @param {object} commandIntent - JSON from AI agent
 * @returns {object} { payload, commandType }
 * @throws {Error} If no valid payload found
 */
export const extractPayload = (commandIntent) => {
  if (!commandIntent || typeof commandIntent !== 'object') {
    throw new Error('INVALID_INTENT: Expected JSON object');
  }

  // Search paths for payload (in priority order)
  const paths = [
    'payload',
    'data.payload',
    'execution.payload',
    'command.payload',
    'data',
    'action.payload'
  ];

  let extracted = null;
  let foundPath = null;

  for (const path of paths) {
    const keys = path.split('.');
    let current = commandIntent;
    let valid = true;

    for (const key of keys) {
      if (current && typeof current === 'object' && key in current) {
        current = current[key];
      } else {
        valid = false;
        break;
      }
    }

    if (valid && current !== null && typeof current === 'object') {
      extracted = current;
      foundPath = path;
      break;
    }
  }

  if (!extracted) {
    throw new Error('PAYLOAD_NOT_FOUND: No execution payload in command intent');
  }

  // Sanitize - remove sensitive fields
  const sanitized = { ...extracted };
  const sensitiveFields = ['rawCommand', 'commandString', 'shellCommand', 'raw', 'script', 'cmd'];
  
  for (const field of sensitiveFields) {
    if (field in sanitized) {
      delete sanitized[field];
    }
  }

  // Determine command type
  const commandType = commandIntent.type || 
                     commandIntent.command?.type || 
                     commandIntent.action?.type || 
                     'unknown';

  return {
    payload: sanitized,
    commandType,
    sourcePath: foundPath
  };
};

// ============================================================================
// INTERCEPTOR SERVICE
// ============================================================================

/**
 * AI Command Interceptor
 * Main function: intercepts command intent, extracts payload, encrypts it
 * 
 * @param {object} commandIntent - JSON from AI agent
 * @param {string} encryptionKey - Hex-encoded 256-bit key
 * @returns {SecurePayload} Encrypted payload ready for transmission
 */
export const interceptCommand = async (commandIntent, encryptionKey, debugLog = null) => {
  console.log('[AI Interceptor] Processing command intent...');

  try {
    // Step 1: Extract and sanitize payload
    const { payload, commandType } = extractPayload(commandIntent);
    
    // Step 2: Inject replay attack prevention fields
    const timestamp = Date.now();
    const nonce = await generateUUIDv4();
    
    const securedPayload = {
      ...payload,
      timestamp,
      nonce,
    };

    // Step 3: Serialize
    const payloadString = JSON.stringify(securedPayload);
    
    if (debugLog) {
      debugLog('Plaintext (before encryption)', JSON.stringify(securedPayload, null, 2));
    }

    // Step 4: Encrypt (Native AES-GCM)
    const encrypted = await encryptPayload(payloadString, encryptionKey);
    console.log('[AI Interceptor] Payload encrypted');

    // Step 5: Create secure container 
    // IMPORTANT: Ensure your SecurePayload class uses (ciphertext, iv, authTag...)
    const securePayload = new SecurePayload(
      encrypted.ciphertext,
      encrypted.iv,
      encrypted.authTag, 
      timestamp,
      { commandType, nonce }
    );

    // Step 6: Security check
    const serialized = JSON.stringify(securePayload.toJSON());
    if (serialized.includes(payloadString)) {
      throw new Error('SECURITY_VIOLATION: Plaintext detected in output');
    }

    console.log('[AI Interceptor] Secure payload ready');
    
    // ✅ ONLY ONE RETURN AT THE VERY END
    return securePayload;

  } catch (error) {
    console.error('[AI Interceptor] Interception failed:', error.message);
    throw error;
  }
};
/**
 * Send encrypted payload to server
 * 
 * @param {SecurePayload} securePayload 
 * @param {string} serverUrl - Server base URL
 * @returns {Promise<object>} Server response
 */
export const sendToServer = async (securePayload, serverUrl, token) => {
  // Use getBaseUrl if provided, but ensure we don't double up on /api
  const baseUrl = serverUrl.endsWith('/api') ? serverUrl : `${serverUrl}/api`;
  const url = `${baseUrl}/execute`;
  const requestId = generateRandomHex(8);

  try {
    console.log(`[AI Interceptor] Sending to: ${url}`);

    // Inside sendToServer in AICommandInterceptor.js
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-Request-ID': requestId,
        'X-Client-Version': '1.0.0',
        // Add this line to prepare for Claude's new security middleware!
        'Authorization': `Bearer ${token}` 
      },
      body: JSON.stringify(securePayload.toJSON())
    });

    // ✅ READ THE BODY ONCE HERE
    const responseText = await response.text();
    let responseData;

    try {
      responseData = JSON.parse(responseText);
    } catch (e) {
      responseData = { message: responseText };
    }

    if (!response.ok) {
      throw new Error(`SERVER_ERROR: ${response.status} - ${responseData.message || 'Unknown'}`);
    }

    console.log('[AI Interceptor] Server acknowledged');

    return {
      success: true,
      requestId,
      status: response.status,
      data: responseData // Use the already-parsed data
    };

  } catch (error) {
    console.error('[AI Interceptor] Send failed:', error.message);
    if (error.message.includes('NETWORK') || error.message.includes('fetch')) {
      throw new Error('NETWORK_ERROR: Unable to reach server');
    }
    throw error;
  }
};

/**
 * Complete workflow: intercept, encrypt, and send
 * 
 * @param {object} commandIntent - JSON from AI agent
 * @param {string} encryptionKey - Hex-encoded 256-bit key
 * @param {string} serverUrl - Server base URL
 * @returns {Promise<object>} Result
 */
export const interceptAndSend = async (commandIntent, encryptionKey, serverUrl, token, debugLog = null) => {
  try {
    const securePayload = await interceptCommand(commandIntent, encryptionKey, debugLog);
    const result = await sendToServer(securePayload, serverUrl, token);
    
    return {
      success: true,
      timestamp: securePayload.timestamp,
      metadata: securePayload.metadata,
      serverResponse: result
    };
  } catch (error) {
    return {
      success: false,
      error: error.message,
      timestamp: Date.now()
    };
  }
};

// ============================================================================
// EXPORT DEFAULT
// ============================================================================

export default {
  generateEncryptionKey,
  generateIV,
  encryptPayload,
  decryptPayload,
  SecurePayload,
  extractPayload,
  interceptCommand,
  sendToServer,
  interceptAndSend
};
